Not Updated for latest version
lyuha/MHW-split pull request #2
Opened 2022-02-20 14:45 UTC by Majwt

Added new Pointes for the latest version of the game

2022-05-09 14:56 UTC, lyuha commented
It's not work.

2022-05-10 12:55 UTC, Majwt commented
Ok that's weird. It worked for me but I'll test again later.

2022-05-10 14:06 UTC, Majwt commented
I found the problem! On line 39, `int questID : "MonsterHunterWorld.exe",0x0506F240,0x4C,0x14000000;`
The `0x14000000` should not be there, then it works.

Should i close this and make a new pull request or will you merge and remove the fault manually?

2022-05-11 00:04 UTC, lyuha commented
Please update code and push again to your repository with same branch!
If you push [Majwt/issue1](https://github.com/Majwt/MHW-split/tree/Majwt/issue1) and it works, I will merge this PR!

Thanks to report issue and PR!

2022-05-11 10:01 UTC, Majwt commented
Done!

2022-05-11 13:30 UTC, lyuha requested changes

2022-05-11 13:30 UTC, lyuha commented on monster-hunter-world.asl
>      float sessionTime: "MonsterHunterWorld.exe",0x0506F240,0x90,0x46A0,0x14;
Update this line!

Needs change sessionTime pointer.
Check This [CE table](https://opencheattables.org/viewtopic.php?f=12&t=20&p=31&hilit=monster+hunter+world#p31)

2022-05-11 15:10 UTC, Majwt commented
Now it is done, I hope.

2022-05-12 13:55 UTC, merged

2022-05-12 13:55 UTC, lyuha commented
It's works!
Thanks to PR!